networks:
  proxy:
    external: true

services:
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    hostname: pihole
    restart: unless-stopped
    network_mode: host
    environment:
      TZ: "America/New_York"
      FTLCONF_webserver_port: "8888" 
      FTLCONF_webserver_api_password: "somethingNo1WouldGuessRight?"
      FTLCONF_dns_upstreams: "1.1.1.1;8.8.8.8"
      FTLCONF_dns_listeningMode: "local"
    volumes:
      - ./etc-pihole:/etc/pihole
      - ./etc-dnsmasq.d:/etc/dnsmasq.d
